	nios_system u0 (
		.clk_clk                (<connected-to-clk_clk>),                //             clk.clk
		.cueball_export         (<connected-to-cueball_export>),         //         cueball.export
		.eightball_export       (<connected-to-eightball_export>),       //       eightball.export
		.elevenball_export      (<connected-to-elevenball_export>),      //      elevenball.export
		.fifteenball_export     (<connected-to-fifteenball_export>),     //     fifteenball.export
		.fiveball_export        (<connected-to-fiveball_export>),        //        fiveball.export
		.fourball_export        (<connected-to-fourball_export>),        //        fourball.export
		.fourteenball_export    (<connected-to-fourteenball_export>),    //    fourteenball.export
		.keycode_export         (<connected-to-keycode_export>),         //         keycode.export
		.nineball_export        (<connected-to-nineball_export>),        //        nineball.export
		.oneball_export         (<connected-to-oneball_export>),         //         oneball.export
		.otg_hpi_address_export (<connected-to-otg_hpi_address_export>), // otg_hpi_address.export
		.otg_hpi_cs_export      (<connected-to-otg_hpi_cs_export>),      //      otg_hpi_cs.export
		.otg_hpi_data_in_port   (<connected-to-otg_hpi_data_in_port>),   //    otg_hpi_data.in_port
		.otg_hpi_data_out_port  (<connected-to-otg_hpi_data_out_port>),  //                .out_port
		.otg_hpi_r_export       (<connected-to-otg_hpi_r_export>),       //       otg_hpi_r.export
		.otg_hpi_w_export       (<connected-to-otg_hpi_w_export>),       //       otg_hpi_w.export
		.poolcue_export         (<connected-to-poolcue_export>),         //         poolcue.export
		.reset_reset_n          (<connected-to-reset_reset_n>),          //           reset.reset_n
		.sdram_clk_clk          (<connected-to-sdram_clk_clk>),          //       sdram_clk.clk
		.sdram_wire_addr        (<connected-to-sdram_wire_addr>),        //      sdram_wire.addr
		.sdram_wire_ba          (<connected-to-sdram_wire_ba>),          //                .ba
		.sdram_wire_cas_n       (<connected-to-sdram_wire_cas_n>),       //                .cas_n
		.sdram_wire_cke         (<connected-to-sdram_wire_cke>),         //                .cke
		.sdram_wire_cs_n        (<connected-to-sdram_wire_cs_n>),        //                .cs_n
		.sdram_wire_dq          (<connected-to-sdram_wire_dq>),          //                .dq
		.sdram_wire_dqm         (<connected-to-sdram_wire_dqm>),         //                .dqm
		.sdram_wire_ras_n       (<connected-to-sdram_wire_ras_n>),       //                .ras_n
		.sdram_wire_we_n        (<connected-to-sdram_wire_we_n>),        //                .we_n
		.sevenball_export       (<connected-to-sevenball_export>),       //       sevenball.export
		.sixball_export         (<connected-to-sixball_export>),         //         sixball.export
		.tenball_export         (<connected-to-tenball_export>),         //         tenball.export
		.thirteenball_export    (<connected-to-thirteenball_export>),    //    thirteenball.export
		.threeball_export       (<connected-to-threeball_export>),       //       threeball.export
		.twelveball_export      (<connected-to-twelveball_export>),      //      twelveball.export
		.twoball_export         (<connected-to-twoball_export>),         //         twoball.export
		.sys_reset_export       (<connected-to-sys_reset_export>),       //       sys_reset.export
		.hw_sig_export          (<connected-to-hw_sig_export>),          //          hw_sig.export
		.stick_direction_export (<connected-to-stick_direction_export>)  // stick_direction.export
	);

